version: "3.9"

services:
  nats:
    image: nats:2.10-alpine
    command:
      - "-js"
      - "--sd"
      - "/data/jetstream"
      - "--http_port"
      - "8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-js-data:/data/jetstream
    restart: unless-stopped

volumes:
  nats-js-data:

