name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  lint-and-test:
    name: Lint и тесты
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Установка Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      # - name: Кеш модулей
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.cache/go-build
      #       ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-

      - name: Установка зависимостей
        run: go mod download

      - name: Линт (golangci-lint)
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.4
          args: --timeout=5m

      - name: run jetstream
        run: |
          docker run --name nats-server -p 4222:4222 -p 8222:8222 -d nats:2.12.0 -js --http_port 8222

      - name: Тесты
        env:
          NATS_URL: nats://127.0.0.1:4222
        run: go test ./...

      - name: stop jetstream
        run: docker stop nats-server
        if: always()
